# Generated by Django 5.2.12 on 2026-04-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_customuser_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="sex",
            field=models.CharField(
                choices=[("여자", "여자"), ("남자", "남자")],
                default="여자",
                max_length=10,
                verbose_name="성별",
            ),
        ),
    ]
