# Generated by Django 5.2.12 on 2026-05-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
