# Generated by Django 5.2.12 on 2026-05-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_id_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="header/"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
