# Generated by Django 5.2.12 on 2026-05-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_header_image_user_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="id_name",
            new_name="nickname",
        ),
    ]
