# Generated by Django 5.2.12 on 2026-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="language",
        ),
        migrations.AddField(
            model_name="post",
            name="expiration_date",
            field=models.DateField(default="2026-04-09"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="gender",
            field=models.IntegerField(choices=[(1, "woman"), (2, "man")], default=1),
        ),
        migrations.AddField(
            model_name="post",
            name="open_date",
            field=models.DateField(default="2026-04-09"),
            preserve_default=False,
        ),
    ]
