# Generated by Django 5.2.12 on 2026-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_remove_post_language_post_expiration_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="audit.hashtag"
            ),
        ),
    ]
