# Generated by Django 5.2.12 on 2026-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_hashtag_post_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="post_photo"),
        ),
    ]
