# Generated by Django 5.2.12 on 2026-03-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(to="audit.hashtag"),
        ),
    ]
