# Generated by Django 5.2.12 on 2026-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_post_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(blank=True, to="audit.hashtag"),
        ),
    ]
