# Generated by Django 5.2.12 on 2026-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("category", models.CharField(default="기타", max_length=20)),
                ("expiration_date", models.DateField()),
                ("opened_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
