# Generated by Django 5.2.12 on 2026-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashtag", models.CharField(max_length=100)),
            ],
        ),
    ]
