# Generated by Django 5.2.12 on 2026-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_post_hashtag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Inventory",
        ),
        migrations.AlterField(
            model_name="post",
            name="expiration",
            field=models.DateField(),
        ),
    ]
