# Generated by Django 5.2.12 on 2026-04-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="sex",
            field=models.CharField(
                choices=[("여자", 0), ("남자", 1)],
                default="여자",
                max_length=10,
                verbose_name="성별",
            ),
        ),
    ]
